{
 "title": "Spring Cloud Gateway - new",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": {
     "query": "label_values(gateway_requests_seconds_count,job)"
    }
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": {
     "query": "label_values(gateway_requests_seconds_count,routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=~\"api-gateway\"})"
    }
   ]
  },
  {
   "title": "Total Successful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"api-gateway\"})"
    }
   ]
  },
  {
   "title": "Total Unsuccessful Requests Served",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"api-gateway\"})"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "member",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"member-service\", job=~\"api-gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"member-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "guest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"guest-service\", job=~\"api-gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"guest-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "problem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"problem-service\", job=~\"api-gateway\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"problem-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Successful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "member Success API Gateway Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"member-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "guest Success API Gateway Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"guest-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "problem Success API Gateway Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"problem-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "Unsuccessful API Calls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "member Unsuccessful GW Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"member-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "guest Unsuccessful GW Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"guest-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "problem Unsuccessful GW Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"problem-service\", job=~\"api-gateway\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  {
   "title": "API / HTTP Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "member",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"member-service\", job=~\"api-gateway\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  {
   "title": "guest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"guest-service\", job=~\"api-gateway\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  {
   "title": "problem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"problem-service\", job=~\"api-gateway\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$gatewayService\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}